language: python
python: 3.6
dist: trusty
sudo: false

services:
  - docker

env:
  - TOXENV=py36

cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/.tox --recreate

install:
  - pip install -U pip
  - pip install -U tox
  - sudo apt-get remove sqlite3
  - wget https://www.sqlite.org/2018/sqlite-autoconf-3260000.tar.gz && tar xzf sqlite.tar.gz
  - cd $TRAVIS_BUILD_DIR/sqlite && ./configure --prefix=/usr --disable-static CFLAGS="-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_SOUNDEX -DSQLITE_TEMP_STORE=3 -DSQLITE_USE_URI -O2 -fPIC"
  - cd $TRAVIS_BUILD_DIR/sqlite && make
  - cd $TRAVIS_BUILD_DIR/sqlite && sudo make install
# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

