language: python
python: 3.6
dist: trusty
sudo: false

services:
  - docker

env:
  - TOXENV=py36

cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/.tox --recreate

# before_install:
#  - sudo apt-get install -y realpath  #  travis-dockerized-solc.bash
#  - export SOLC_BINARY=`pwd`/script/travis-dockerized-solc.bash
#  - docker pull ethereum/solc:0.4.18
#  - echo "Using solc $SOLC_BINARY"
#  - $SOLC_BINARY --version  # Show that solc is acting somewhat sane

install:
  - travis_retry pip install setuptools --upgrade
  - pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}


