language: python
python: 3.6
dist: trusty
sudo: false

services:
  - docker

env:
  - TOXENV=py36

cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/.tox --recreate

install:
  - pip install -U pip
  - pip install -U tox
  - sudo apt-get remove sqlite3
# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

